### ISSUE TITLE
Parsing TSX files

### ISSUE THREAD

**Issue by Phantas0s** [oakes/tile-soup#1]
Nice work you did with tile-soup! 

I was playing with tiled and I was wondering if it would make sense to the tileset files (.tsx) if declared in the tilemap.

Having both the tileset and the tilemap in the same map would be nice for tile custom properties, for example.

I could try to implement that if I have a bit of time. I just wanted to know what you were thinking about the idea.

I'm new to Clojure, I have no clue about spec, so don't expect the best work ever, *if* I do it :smiley:

**Comment by oakes** [comment]
I probably won't have tile-soup automatically retrieve external files like tsx because the way you retrieve it will depend on your environment. In clojurescript, you will need to do an ajax request, and in clojure you'll probably either be reading it from resources with `clojure.java.io/resource` or just `slurp`ing it from the disk. So it's probably best not to put that in tile-soup itself.

But i think i can make it easier to parse with a small change to tile-soup. Right now, the [parse function](https://github.com/oakes/tile-soup/blob/f368125debc3c92df1d8a9f8e6f9f58338b61da7/src/tile_soup/core.cljc#L25) is hard-coded to use the `::map/map` spec, but maybe i can make it possible to pass any spec there. That way, you can make it parse with the tileset spec, which is what tsx files need. I'll experiment with this and see if it works.

**Comment by oakes** [comment]
OK that was easier than i thought. I released 0.4.0 with the change to the parse function. I added an example near the end of the docs, where it says "parsing a TSX file":

https://oakes.github.io/tile-soup/

Like i said, you'll still need to retrieve it yourself, but that should allow you to parse it afterwards.

**Comment by Phantas0s** [comment]
It makes sense. Thanks a lot!

**Comment by oakes** [comment]
BTW i had another thought: with clojurescript you don't necessarily need to retrieve it with ajax. In the super koalio example, the tiled map is being read by [a macro](https://github.com/oakes/play-cljc-examples/blob/46749aa0de2acfc3a9a688e9f0915d0ed8d176dc/super-koalio/src/super_koalio/tiles.cljc#L11-L16) which runs at compile time, so it's running on the JVM, not in the browser. That means you could actually just read the TSX file in that macro, parse it, and add it somewhere in the overall hash map (right before the `pr-str`). That way, when the game loads, it has everything it needs and doesn't need to retrieve anything else.

**Comment by Phantas0s** [comment]
It's exactly what I wanted to do. It's how I handled loading levels in my sokoban game. The downside is you can't pass a symbol or a procedure because the macro doesn't eval the argument. Other than that, it works well.

Thanks for the tip anyway :) I went through super koalio many times to understand how everything is working.
